DROP TABLE IF EXISTS Bookmarks;
DROP TABLE IF EXISTS History;

CREATE TABLE IF NOT EXISTS Bookmarks(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    url TEXT NOT NULL,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS History(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    url TEXT NOT NULL,
    timestamp TEXT NOT NULL
);